Atualiza workflows

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -18,57 +18,72 @@ defaults:
 
 jobs:
 
-  code-analysis:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v3
+    meta:
+      runs-on: ubuntu-latest
+      outputs:
+        ENVIRONMENT: ${{ steps.vars.outputs.ENVIRONMENT }}
+        STACK_NAME: ${{ steps.vars.outputs.STACK_NAME }}
+      steps:
+        - name: Checkout
+          uses: actions/checkout@v4
 
-      - name: Update Global Yarn
-        run: |
-          corepack enable
-          corepack prepare yarn@stable --activate
+        - name: Set Env Vars
+          id: vars
+          run: |
+            ENVIRONMENT=${{ vars.LIVE_ENV }}
+            echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_OUTPUT
+            echo "STACK_NAME=${ENVIRONMENT//./-}" >> $GITHUB_OUTPUT
 
-      - name: Use Node.js ${{ env.node-version }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ env.NODE_VERSION }}
-          cache: 'yarn'
-          cache-dependency-path: 'frontend/yarn.lock'
+    code-analysis:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout codebase
+          uses: actions/checkout@v3
 
-      - name: Prettier
-        id: prettier
-        run: npx prettier@3.0.3 --single-quote --check 'src/**/*.{js,jsx,ts,tsx,css,scss}' --config=package.json
+        - name: Update Global Yarn
+          run: |
+            corepack enable
+            corepack prepare yarn@stable --activate
 
-      - name: Install packages
-        run: make install
+        - name: Use Node.js ${{ env.node-version }}
+          uses: actions/setup-node@v3
+          with:
+            node-version: ${{ env.NODE_VERSION }}
+            cache: 'yarn'
+            cache-dependency-path: 'frontend/yarn.lock'
 
-      - name: ESLint
-        id: eslint
-        if: ${{ success() || failure() }}
-        run: yarn run lint:ci
+        - name: Prettier
+          id: prettier
+          run: npx prettier@3.0.3 --single-quote --check 'src/**/*.{js,jsx,ts,tsx,css,scss}' --config=package.json
 
-      - name: i18n sync
-        id: i18n
-        if: ${{ success() || failure() }}
-        run: make i18n-ci
+        - name: Install packages
+          run: make install
 
-      - name: Unit Tests
-        id: unit
-        if: ${{ success() || failure() }}
-        run: make test
+        - name: ESLint
+          id: eslint
+          if: ${{ success() || failure() }}
+          run: yarn run lint:ci
 
-      - name: Report
-        if: ${{ success() || failure() }}
-        run: |
-          echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
-          echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
-          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
-          echo '| Prettier | ${{ steps.prettier.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
-          echo '| ESLint | ${{ steps.eslint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
-          echo '| i18n | ${{ steps.i18n.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
-          echo '| Unit Tests | ${{ steps.unit.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY 
+        - name: i18n sync
+          id: i18n
+          if: ${{ success() || failure() }}
+          run: make i18n-ci
 
+        - name: Unit Tests
+          id: unit
+          if: ${{ success() || failure() }}
+          run: make test
+
+        - name: Report
+          if: ${{ success() || failure() }}
+          run: |
+            echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
+            echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
+            echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
+            echo '| Prettier | ${{ steps.prettier.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| ESLint | ${{ steps.eslint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| i18n | ${{ steps.i18n.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Unit Tests | ${{ steps.unit.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY 
 
   release:
     runs-on: ubuntu-latest
@@ -120,3 +135,30 @@ jobs:
           push: ${{ github.event_name != 'pull_request' }}
           tags: ${{ steps.meta.outputs.tags }}
           labels: $${{ steps.meta.outputs.labels }}
+
+  deploy:
+    if: ${{ github.ref == 'refs/heads/main' }}
+    needs:
+      - meta
+      - release
+    runs-on: ubuntu-latest
+    environment: ${{ needs.meta.outputs.ENVIRONMENT }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Deploy to cluster
+        uses: kitconcept/docker-stack-deploy@v1.2.0
+        with:
+          registry: "ghcr.io"
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+          remote_host: ${{ secrets.DEPLOY_HOST }}
+          remote_port: ${{ secrets.DEPLOY_PORT }}
+          remote_user: ${{ secrets.DEPLOY_USER }}
+          remote_private_key: ${{ secrets.DEPLOY_SSH }}
+          stack_file: devops/stacks/${{ needs.meta.outputs.ENVIRONMENT }}.yml
+          stack_name: ${{ needs.meta.outputs.STACK_NAME }}
+          stack_param: ${{ github.ref_name }}
+          env_file: ${{ secrets.ENV_FILE }}
+          deploy_timeout: 480
